version: "3.8"
services:
  fastapi:
    depends_on:
      - postgres
    build: backend
    container_name: "container-fastapi"
    env_file:
      - .env_fastapi
    volumes:
      - ./backend/src:/opt
    ports:
      - "8000:80"
    networks:
      - webnet

  postgres:
    image: postgres:alpine
    container_name: "container-postgres"
    env_file:
     - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - 5432:5432
    networks:
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge
