version: "3.7"

services:
  fastapi:
    depends_on:
      - postgres
    build: backend
    container_name: "container-fastapi"
    volumes:
      - ./backend/src:/opt
    ports:
      - "8000:80"
    networks:
      - webnet

  postgres:
    image: postgres:alpine
    container_name: "container-postgres"
    env_file:
     - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_backup:/opt/db_backup
    networks:
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge
volumes:
  pgdata:
